#!/usr/bin/env bash

#./run_tests -- -c nose.cfg

function usage {
  echo "Usage: $0 [OPTION]..."
  echo "Run Tempest test suite"
  echo ""
  echo "  -p, --pep8               Just run pep8"
  echo "  -h, --help               Print this usage message"
  echo "  -- [NOSEOPTIONS]         After the first '--' you can pass arbitrary arguments to nosetests "
}


do_pep8=0

if ! options=$(getopt -o VNnfuswcphdSC:lL: -l virtual-env,no-virtual-env,no-site-packages,force,update,smoke,whitebox,nova-coverage,pep8,help,debug,stdout,config:,logging,logging-config: -- "$@")
then
    # parse error
    usage
    exit 1
fi

eval set $options
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) usage; exit;;
    -p|--pep8) let do_pep8=1;;
    *) noseargs="$noseargs $1"
  esac
  shift
done

NOSETESTS="nosetests $noseargs"
FUNCTIONAL=tests/functional
UNIT=tests/units

function run_unit_tests {
  ${wrapper} $NOSETESTS $UNIT
}

function run_functional_tests {
  ${wrapper} $NOSETESTS $FUNCTIONAL
}

function run_pep8 {
  echo "Running pep8 ..."
  ${wrapper} flake8
}

if [ $do_pep8 -eq 1 ]; then
    run_pep8
    exit
fi

run_unit_tests
#run_functional_tests
retval=$?

exit $retval
