#!/usr/bin/env python
#
# Plugin to monitor numeter collector
#
# E.g.
#    ln -s /usr/share/munin/plugins/numeter_collector_stats /etc/munin/plugins/numeter_collector_stats
#
# Magic markers
#%# capabilities=autoconf
#%# family=auto
#
#  [numeter_*]
#  env.collectorLog
#  env.collectorPattern
#  env.grepPattern

import sys
import os
import subprocess
import re

try: 
    from numeter_collector import myCollector
except ImportError:
    import_collector = False
else:
    import_collector = True

def print_config(check_type):
    print 'graph_title Numeter collector stats'
    print 'graph_info This graph shows collector stats'
    print 'graph_vlabel value'
    print 'graph_args --base 1000 --lower-limit 0'
    print 'graph_category numeter'
    for name in check_type:
        print '%s.label %s' % (name, name)
        print '%s.draw LINE' % name
        print '%s.info %s value' % (name, name)
        if name == "collectors":
            print '%s.color #909122' % name
        elif name == "hosts":
            print '%s.color #67809e' % name
        elif name == "plugins":
            print '%s.color #53b73a' % name
        elif name == "datas":
            print '%s.color #0327ca' % name
        elif name == "seconds":
            print '%s.color #7347ba' % name

def load_params():
# Sample log output:
# ---- End : numeter_collector, 1 collector, 1 Hosts, 31 Plugins, 150 Datas in 0.0824151039124, seconds.
    global  COLLECTOR_LOG, COLLECTOR_PATTERN
    global  GREP_PATTERN
    COLLECTOR_LOG      = os.getenv('collectorLog',
                                 '/var/log/numeter/numeter-collector.log')
    COLLECTOR_PATTERN  = os.getenv('collectorPattern',
                                 '.*---- End : numeter_collector, '
                                 + '([0-9\.]+) plugins, '
                                 + '([0-9\.]+) hosts, '
                                 + '([0-9\.]+) datas in '
                                 + '([0-9\.]+), seconds')
    GREP_PATTERN     = os.getenv('grepPattern',
                                 ' End : numeter_') # For performance 

def get_file_line():
    "Return the last matching line in log file"
    stdout = subprocess.Popen('grep "' + GREP_PATTERN + '" ' + COLLECTOR_LOG
                              + ' 2>/dev/null | tail -1',
                              shell=True,
                              stdout=subprocess.PIPE)
    return stdout.communicate()[0]

def get_value_in_line(name,line):
    # 0 data / 1 error
    result = re.match(COLLECTOR_PATTERN, line)
    if result is not None:
        idx = check_type.index(name) + 1
        if result.group(idx) is not None:
            return str(result.group(idx))
    else:
        return None

def print_value_collector(name, value):
    if value is None:
        value = 'U'
    print '%s.value %s' % (name, value)


if __name__ == '__main__':
    argv = sys.argv[:]
    # Disable seconds
    check_type = ['plugins','hosts','datas']
    if len(argv) > 1:
        if argv[1] == 'config':
            print_config(check_type)
        elif argv[1] == 'autoconf':
            if not import_collector:  
                print 'no (failed import collector module)'
                sys.exit(0)
            print 'yes'
    elif import_collector:
        load_params()
        fileline = get_file_line()
        for name in check_type: 
            value = get_value_in_line(name,fileline)
            print_value_collector(name,value)
