#!/usr/bin/env python
#
# Plugin to monitor the time since the last rrd clean for the numeter storage
#
# Magic markers
#%# capabilities=autoconf
#%# family=auto
#
#  [numeter_storage_last_rrd_clean]
#  env.redisKey
#  env.redisHost
#  env.redisPort
#  env.redisTimeout
#  env.redisDb
#  env.redisPassword

import sys
import os
import time
import datetime

try: 
    from numeter_storage import myStorage
except ImportError:
    IMPORT_STORAGE = False
else:
    IMPORT_STORAGE = True

try: 
    from myRedisConnect import *
except ImportError:
    IMPORT_REDIS = False
else:
    IMPORT_REDIS = True

def print_config():
    print 'graph_title Numeter storage last rrd clean'
    print 'graph_info This graph shows time since the last rrd clean'
    print 'graph_vlabel Seconds'
    print 'graph_args --base 1000 --lower-limit 0'
    print 'graph_category numeter'
    print 'lastrrdcleanclean.label lastrrdclean'
    print 'lastrrdcleanclean.draw LINE'
    print 'lastrrdcleanclean.info lastrrdclean Time'
    print 'lastrrdcleanclean.color #909122'

def load_params():
    global REDIS_KEY
    global REDIS_HOST
    global REDIS_PORT
    global REDIS_TIMEOUT
    global REDIS_DB
    global REDIS_PASSWORD

    REDIS_KEY       = os.getenv('redisKey','LAST_RRD_CLEAN')
    REDIS_HOST      = os.getenv('redisHost', '127.0.0.1')
    REDIS_PORT      = os.getenv('redisPort', 6379)
    REDIS_TIMEOUT   = os.getenv('redisTimeout', 10)
    REDIS_DB        = os.getenv('redisDb', 2)
    REDIS_PASSWORD  = os.getenv('redisPassword', None)


def print_values():
    redis_connexion = myRedisConnect(host=REDIS_HOST,
                      port=REDIS_PORT,
                      socket_timeout=REDIS_TIMEOUT,
                      db=REDIS_DB,
                      password=REDIS_PASSWORD)

    if redis_connexion._error:
        print("Redis server connexion ERROR - "
        + "Check server access or the password")
        exit(1)

    lastfetch = redis_connexion.redis_get(REDIS_KEY)

    if not lastfetch:
        print "lastrrdcleanclean.value U"
        sys.exit(1)
    timenow = datetime.datetime.now()
    timenow = time.mktime(timenow.timetuple())
    lastclean = timenow - int(lastfetch)

    print 'lastrrdcleanclean.value', lastclean


if __name__ == '__main__':
    ARGV = sys.argv[:]
    if len(ARGV) > 1:
        if ARGV[1] == 'config':
            print_config()
        elif ARGV[1] == 'autoconf':
            if not (IMPORT_REDIS and IMPORT_STORAGE):
                print 'no (failed import redis or storage module)'
                sys.exit(0)
            print 'yes'

    elif IMPORT_REDIS:
        load_params()
        print_values()
