#!/usr/bin/env python

# Need apt-get install python-daemon

import sys
import time
from daemon import runner
from lockfile import LockTimeout
import logging

from numeter.poller import Poller
import ConfigParser

class App():
    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/tty'
        self.stderr_path = '/dev/tty'
        self.pidfile_path =  '/var/run/numeter.poller.pid'
        self.pidfile_timeout = 1.1
        self._poller_time = 60
        # Read poller conf time
        self.poller_configFile = "/etc/numeter/numeter_poller.cfg"
        myConf=self._readConf()
        # Am I enabled in conf
        if myConf.has_option('global', 'enable'):
            if not myConf.getboolean('global', 'enable'):
                print("Poller disabled in config file. Not starting...")
                exit(100)
        # Get poller time
        if myConf.has_option('global', 'poller_time') \
        and myConf.getint('global', 'poller_time'):
            self._poller_time = myConf.getint('global', 'poller_time')

    def _readConf(self):
        "Read configuration file"
        configParse = ConfigParser.RawConfigParser()

        if configParse.read(self.poller_configFile) == []:
            print ("CRIT - Read Config file "
                   + self.poller_configFile
                   + " - ERROR (empty or doesn't exist)")
            exit(1)
        return configParse

    def run(self):
        lastCheckTime = None
        poller = Poller(self.poller_configFile)
        poller.disable_pollerTimeToGo = True
        while True:
            nowTimestamp = "%.0f" % time.time()
            # +5 give you an accuracy of 5 sec more or less between fetch
            if lastCheckTime is None \
            or (int(lastCheckTime)+self._poller_time) <= (int(nowTimestamp)+5):
                poller.startPoller()
                lastCheckTime = nowTimestamp
            time.sleep(1)

app = App()
daemon_runner = runner.DaemonRunner(app)

try:
    daemon_runner.do_action()
except (runner.DaemonRunnerStopFailureError, TypeError) as e:
    print 'PID not found, Already stop. %s' % e
except LockTimeout:
    print 'Lock file found, Already start. %s.lock' % app.pidfile_path
except Exception as e:
    print "Error : %s %s" % (e, str(sys.exc_info()))

