#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# $Id: numeter,v 1.5 2009-07-28 14:31:26 gaelL Exp $
#
#    Copyright (C) 2010-2013 Gaël Lambert (gaelL) <gael.lambert@enovance.com>
#
#    This file is part of numeter
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

""" calls numeter function """

# Need before oslo messaging (oslo/messaging/_cmd/zmq_receiver.py line 19)
import eventlet
eventlet.monkey_patch()

from numeter.storage import Storage

if __name__ == '__main__':
    storage = Storage("/etc/numeter/numeter_storage.cfg")
    storage.startStorage()
    exit(0)
