#!/usr/bin/env python

# Need apt-get install python-daemon

import sys
import time
from daemon import runner
from lockfile import LockTimeout
import logging
import time

from numeter_storage import myStorage
import ConfigParser

class App():
    def __init__(self):
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/null'
        #self.stderr_path = '/dev/tty'
        self.stderr_path = '/dev/null'
        self.pidfile_path =  '/var/run/numeter_storage.pid'
        self.pidfile_timeout = 0.1
        self._storage_time = 60
        # Read storage conf time
        self.storage_configFile = "/etc/numeter/numeter_storage.cfg"
        myConf=self._readConf()
        if myConf.has_option('global', 'enable'):
            if not myConf.getboolean('global', 'enable'):
                print("Poller disabled in config file. Not starting...")
                exit(100)
        # Get storage time
        if myConf.has_option('global', 'storage_time') \
        and myConf.getint('global', 'storage_time'):
            self._storage_time = myConf.getint('global', 'storage_time')

    def _readConf(self):
        "Read configuration file"
        configParse = ConfigParser.RawConfigParser()

        if configParse.read(self.storage_configFile) == []:
            print ("CRIT - Read Config file "
                   + self.storage_configFile
                   + " - ERROR (empty or doesn't exist)")
            exit(1)
        return configParse

    def run(self):
        storage = myStorage(self.storage_configFile)
        lastCheckTime = None
        while True:
            nowTimestamp = "%.0f" % time.time()
            # +5 give you an accuracy of 5 sec more or less between fetch
            if lastCheckTime is None \
            or (int(lastCheckTime)+self._storage_time) <= (int(nowTimestamp)+5):
                storage.startStorage()
                lastCheckTime = nowTimestamp
            time.sleep(1)

app = App()
daemon_runner = runner.DaemonRunner(app)

try:
    daemon_runner.do_action()
except (runner.DaemonRunnerStopFailureError, TypeError):
    print 'PID not found, Already stop.'
except LockTimeout:
    print 'Lock file found, Already start.'
except Exception as e:
    print "Error : %s %s" % (e, str(sys.exc_info()))

